### ISSUE TITLE
Implement <thumbnail />

### ISSUE THREAD

**Issue by Elhebert** [FineUploader/vue-fineuploader#14]
Port the [\<Thumbnail /\>](https://github.com/FineUploader/react-fine-uploader/tree/master/src/components/thumbnail) component from react to Vue 2.

**Comment by infernobass7** [comment]
Is there a timeline for adding this feature?

**Comment by Elhebert** [comment]
Unfortunately, I am quite busy these day and will be, at least until the end of April.

Without making any promise, I'll try to find some time late April, early May to do this.

**Comment by Elhebert** [comment]
closed in #32
