### ISSUE TITLE
Use external wrapper classes (fine-uploader-wrappers)

### ISSUE THREAD

**Issue by Elhebert** [FineUploader/vue-fineuploader#17]
Use the external wrapper classes from https://github.com/FineUploader/react-fine-uploader/issues/21.

**Comment by rnicholus** [comment]
...now published as [`fine-uploader-wrappers`](https://github.com/FineUploader/fine-uploader-wrappers). React Fine Uploader was recently updated to pull in the wrappers from their new location. See FineUploader/react-fine-uploader@980f515ca1ee8a0480457c9512363d9a75f2c567 for details.

**Comment by rnicholus** [comment]
🎉
