### ISSUE TITLE
Does this currently work at all?

### ISSUE THREAD

**Issue by robmpreston** [FineUploader/vue-fineuploader#18]
Sorry not to sound stupid...

From what I've seen the documentation, the package names are wrong, examples are still React based.

But I decided to give it a try

So I npm installed the latest version and when I try to import the files from src/ I get Import errors in my javascript console after the project builds successfully. 

I also didn't see a dist/ folder or anything in node_modules/vue-fineuploader

**Comment by Elhebert** [comment]
Hi,

I just fixed the documentation, thanks for the feedback.

Could you copy/paste the errors you're having here ? I'll look into that issue tonight and try to release a fix asap.

**Comment by Elhebert** [comment]
I just release the `v2.0.0-rc.4` that solved the issue.

Be careful that it introduce some breaking changes. I suggest you read the [release notes](https://github.com/FineUploader/vue-fineuploader/releases/tag/v2.0.0-rc.4)
