### ISSUE TITLE
lodash.IsPlainObject is not listed as a dependency

### ISSUE THREAD

**Issue by msencenb** [FineUploader/vue-fineuploader#27]
Hello!

First - thank you for writing these vue components. It was a huge relief that I found something that was ready to go with fine-uploader and Vue 2. I've been tinkering with it today and so far it's working great.

One snag I ran into was that my webpack compile stumbled on the fact that lodash.isPlainObject was not present. I fixed it by manually including that particular npm module, should that be added as a dependency for this project?

Running Rails 5.1, webpack, and yarn in case that's necessary.

**Comment by Elhebert** [comment]
Good catch, 

I'll see if it possible to get rid of it. Otherwise, I'll add it to the dependencies.
