### ISSUE TITLE
File Input does not take accept prop

### ISSUE THREAD

**Issue by leepercox** [FineUploader/vue-fineuploader#31]
Hey, I am rather new to Vue (I am usually a React dev), so forgive me if I am mistaken. But it seems to me that although your docs state you can pass any "input" prop to File-Input (such as accept), this is not actually the case. It seems you can no longer pass any props so important ones such as accept do not work.

**Comment by Elhebert** [comment]
🤔  That does sound like a VueJS issue. But I'll test my code first, to be sure.

Could you copy/paste the part of the code where you call `<file-input>` ?

Have you checked with the inspector that the attributes where not present on the generated `<input>` ?

**Comment by leepercox** [comment]
Sure. 

```
<template>
        <div class="video-upload-inner">
            <dropzone :uploader="uploader">
                <file-input :uploader="uploader" accept="video/*">
                    <span class="btn">Upload</span>
                </file-input>
            </dropzone>
        </div>
</template>
<script>
  import Dropzone from 'vue-fineuploader/dropzone.vue';
  import FineUploaderS3 from 'fine-uploader-wrappers/s3';
  import FileInput from 'vue-fineuploader/file-input.vue';

  export default {
    components: {
      Dropzone,
      FileInput
    },
    data () {
      const uploader = new FineUploaderS3({
        //... redacted
      });

      return {
        uploader
      }
    },
    name:'VideoUploader',
  }
</script>
```

If you take a look at this file though (Which is your file-input.vue), you never actually pass the props across. Your input only seems to make use of multiple and @change. Nothing else. 

```
<template>
  <div class="vue-fine-uploader-file-input">
    <label>
      <slot>Upload File</slot>
      <input type="file"
             @change="_onFilesSelected"
             :multiple="multiple"/>
    </label>
  </div>
</template>

<style>
  .vue-fine-uploader-file-input {
    display: inline-block;
  }

  .vue-fine-uploader-file-input label {
    cursor: pointer;
  }

  .vue-fine-uploader-file-input input[type="file"] {
    width: 1px;
    height: 1px;
    opacity: 0;
  }
</style>

<script>
  export default {
    props: {
      multiple: {
        type: Boolean,
        default: false
      },
      uploader: {
        type: Object,
        required: true
      }
    },

    data () {
      return {
        _unmounted: false
      }
    },

    beforeDestroy () {
      this._unmounted = true
    },

    methods: {
      _onFilesSelected (e) {
        this.uploader.methods.addFiles(e.target)
      }
    }
  }
</script>

```
I am using version: 
`"vue-fineuploader": "^2.0.0-rc.6",`


Like I say, I have only been using VueJS for like a day. So if I am wrong and Vue can do something fancy to pass props without any code, I apologise. But it just looks to me as being a React dev that the props are not being used at all in your component regardless of if they are passed.

**Comment by leepercox** [comment]
Looking at the react version they do apply the props with the spread operator:

```
import React from 'react'

const containerStyle = {
    display: 'inline-block',
    position: 'relative'
}

const inputStyle = {
    bottom: 0,
    cursor: 'pointer',
    height: '100%',
    left: 0,
    margin: 0,
    opacity: 0,
    padding: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%'
}

const StyleableFileInput = ({ children, className, onChange, ...params }) => (
    <div className={ `react-fine-uploader-file-input-container ${className || ''}` } 
         style={ containerStyle }
    >
        { children }
        <input { ...params }
               className='react-fine-uploader-file-input'
               onChange={ onChange }
               style={ inputStyle }
               type='file'
        />
    </div>
)

export default StyleableFileInput
```

See the ...params on the <input>

**Comment by Elhebert** [comment]
In VueJS, any attributes you set on the components is automatically passed down to the root element.

As explained here: https://vuejs.org/v2/guide/components.html#Non-Prop-Attributes

I'll do some testing later today, but if the attributes aren't passed down, it's a VueJS issue, and should be reported on it's [Github Repository](https://github.com/vuejs/vue)

**Comment by leepercox** [comment]
Ah, that's my misunderstanding of VueJS then there. However, the problem is still there that even if the accept parameter is added, it is not making use of it. I will do some more digging later when I get around to it, see if I am just doing anything stupid. 

I should stick to React :P

**Comment by Elhebert** [comment]
I had time to do some tests, and indeed there's is an issue with the `file-input` component.

The input isn't the root element, thus, the attributes where not passed to it. I'll add the possible attributes as `props` and add them to the `<input>`.
