### ISSUE TITLE
Is it possible to override the default config ?

### ISSUE THREAD

**Issue by minedun6** [FineUploader/vue-fineuploader#39]
Is it possible to override the default ajax provider ?
I need to set axios instead of the default one.
Or is it possible to add headers to the request ?
I need to add csrf token or if I could just override the defaults and use axios since I have headers set by default ?

**Comment by Elhebert** [comment]
This is related to FineUploader.

As stated in the documentation, I use fine-uploader-wrapper ([documentation](https://github.com/FineUploader/fine-uploader-wrappers#constructor-options--2)).

And to answer your question, you can set custom headers.
