### ISSUE TITLE
Vue + Fine Uploader = cool

### ISSUE THREAD

**Issue by rnicholus** [FineUploader/vue-fineuploader#4]
While I'm not _yet_ a user of Vue, it's very exciting to see an integration with Fine Uploader. Please do let me know if you run into any Fine Uploader related issues getting this to work. I'd be happy to help.

**Comment by Elhebert** [comment]
Hi @rnicholus !

First of all, let me thank you for FineUploader, it was the library I was looking for. Great job with that ! I'll be sure to submit an issue if I ran into some problems.

If you have any suggestion that could improve this integration, I'll try to do my best 😉

**Comment by Elhebert** [comment]
Hey there !

I'm reworking my whole vue integration, using your react implementation as base (the frameworks are quite similar). I'll port all the react component you did for Vue 2. It'll be way better than my very basic component that I have at the moment.

If you are interested, the code is there: https://github.com/Elhebert/vue-fineuploader/tree/feature/refactor.

**Comment by rnicholus** [comment]
Great idea. I had hoped multiple framework-specific implementations of the same pattern could exist at some point, based off the pattern in react-fine-uploader. I plan to implement the same pattern myself again as a series of web components as well: fine-uploader-web-components. 

Let me know if you have any questions regarding my code.

**Comment by rnicholus** [comment]
Looks like you're making some serious progress here 🎉.

What do you think about moving this into the FineUploader GitHub organization? Of course, I'd add you as a member to the org, and an admin of this repo.

**Comment by Elhebert** [comment]
That would be great.

I still have some work to do, and a lot of testing ^^, but I think that it could already be released as an rc.

At least it'll offer people a better implementation than the one I have currently on npm, and I'll have more useful feedbacks concerning this version.

If you need me to do some modification to my repo to be "compliant" with the ones on the organisation, tell me and I'll adapt it.

**Comment by rnicholus** [comment]
Because GitHub's permissions system sucks, I'll have to transfer this into a "holding" organization, and then transfer it into FineUploader. I'll have permissions setup for you in the FineUploader org ahead of time though. Let me know if you have any questions.

**Comment by rnicholus** [comment]
...please transfer at your convenience to FineUploader-transfer. Once that is done, I can move it into FineUploader.

**Comment by Elhebert** [comment]
I made the transfer, and also released a release candidate of the library.

I still need to implement the thumbnail, fileinput and the gallery. I also need to dive into the VueJS unit tests, might be a godd idea to write some 😆

**Comment by rnicholus** [comment]
Cool, I'll transfer this into FineUploader now.

>released a release candidate of the library

What is the version number? Might be useful to add an npm badge to the README to show the latest published version. Ideally the releases section of the repo would contain info about each release. Please see react-fine-uploader and fine-uploader for examples.

>also need to dive into the VueJS unit tests, might be a good idea to write some

Absolutely. I think unit testing all of these components is very important.

Related, please see FineUploader/react-fine-uploader#21. When this is implemented, it will affect your library too.

**Comment by rnicholus** [comment]
Oh looks like you are maintaining release notes, awesome. I should have looked first. I didn't see any notes for RC2 though.

Anyway, the repo is transferred, as you can see. Can we change this to vue-fine-uploader, to be consistent with the naming of other repos in this org? Since you're already going to release 2.0 in the near future which will contain substantial breaking changes, maybe that is an appropriate time to do this too.

**Comment by Elhebert** [comment]
I tagged it with `v2.0.0-rc.1` (because it is the second version of my implementation), and published it on npm. Then rc-2 when I updated the README. (not sure if that the way I'm supposed to tag my version, not that familiar with version number conventions ^^).

The badge is actually commented inside the README, I kinda forgot to uncomment it when I released the new version ^^. I'll go fix that.

For the name, I was thinking about that too. Consistency is important here.

**Comment by Elhebert** [comment]
This being my first "serious" repo on github, I try to do my best.

For the release notes, of `rc.2`, I haven't written some because it was a simple update of the README, just like `rc.3`.

If I'm doing something "wrong" or if I did a mistake, don't hesitate to notify me 😉

**Comment by rnicholus** [comment]
Don't think anything you're doing is _wrong_, I guess I've just formed some strong opinions over the years of working on Fine Uploader and my other OSS projects. So, I'll share those opinions if you'd like. 

Somewhat of a nitpick - i see RCs as saying "this is done, just want to get some people to test it out". In this case, since more development is needed (components, tests, etc) this sounds more like a beta or alpha release. Also, in most cases, I think you can leave the version number as-is if you're only updating the README. I usually only update the version if actual code changes. And I always follow [semver](http://semver.org/).

**Comment by Elhebert** [comment]
It actually make sense and I'm already familiar with semver. 

For the RCs, I guess I picked it from my former employer that used RCs as beta versions.

Thanks for sharing your opinions.

**Comment by Elhebert** [comment]
Hi @rnicholus,

Truly sorry about the long inactivity here.

Professional situation was really bad, the relationship between me, my manager and my boss were getting horrible, and didn't let me much time for personal projects, nor will to simply develop outside of work. (Yeah, was that bad).

But 🎉 everything is over, got couples of day for myself, got my self a good job within a good team.
Gonna be able to resume my work on vue-fineuploader in the next couples of days.

Anyway, things a better now, sorry for the inactivity.

**Comment by rnicholus** [comment]
Glad to hear you're happy with your new job. No need to apologize. I appreciate all of your work on this.

**Comment by dbezborodovrp** [comment]
Is there a way to get the UUID of uploaded files? The server sends it back in the request, but the "submitted" event only passes an integer identifier.

**Comment by dbezborodovrp** [comment]
Ah, `this.uploader.methods.getUuid(id)` does the trick.
