### ISSUE TITLE
Manually Trigger Uploads

### ISSUE THREAD

**Issue by Vocal** [FineUploader/vue-fineuploader#40]
Hi

i try to run a demo but i need manually upload using a Button, i read document but not example for this.

Please give me a code example,

Thanks for great component.

**Comment by Elhebert** [comment]
From the README:

https://github.com/FineUploader/vue-fineuploader#wrapper-classes:
> More information, such as examples and API documentation, can be found in the README of the fine-uploader-wrappers project.

You can pass in an object that mirrors the format of the Fine Uploader Core options object. The format will change depending on the type of endpoint you are going to use.
