### ISSUE TITLE
On totalProgress jumps back to 0

### ISSUE THREAD

**Issue by inzanez** [FineUploader/vue-fineuploader#44]
Hi

I'm using the "on('totalProgress', (submitted,total) =>..." callback to display progress of the total upload. Somehow it seems that after reaching 100% both the values 'submitted and total' switch back to '0' immediately. Which deliveries a nice NaN for displaying.

Did you ever come across that issue?

**Comment by Elhebert** [comment]
This is a question about fine-uploader itself, not the VueJS wrapper.
