### ISSUE TITLE
Limiting max size of single files and total number of files.

### ISSUE THREAD

**Issue by hifall** [FineUploader/vue-fineuploader#48]
I see questions like this asked about Fineuploader in various places, but I don't see how one can limit max size of single files and total number of files with Vue-Fineuploader. Could you please provide some examples?

Thanks!

**Comment by hifall** [comment]
Found it. Just do:

```
validation: {
    itemLimit: 2,
    sizeLimit: 10 * 1024 * 1024
}
```

**Comment by Elhebert** [comment]
This has nothing to do with the Vue implementation.

It's proper to FineUploader itself.
