### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by aiakane16** [FineUploader/vue-fineuploader#49]
Got Module not found using the given example in read me 

```
<template>
  <Gallery :uploader="uploader" />
</template>

<script>
  import FineUploaderTraditional from 'fine-uploader-wrappers'
  import Gallery from 'vue-fineuploader/gallery'

  export default {
    components: {
      Gallery
    },
    data () {
      const uploader = new FineUploaderTraditional({
        options: {
          deleteFile: {
            enabled: true,
            endpoint: 'my/upload/endpoint'
          },
          request: {
            endpoint: 'my/upload/endpoint'
          }
        }
      })

      return {
        uploader
      }
    }
  }
</script>
```

```
ERROR in ./components/FineUploader.vue?vue&type=script&lang=js (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./components/FineUploader.vue?vue&type=script&lang=js)
Module not found: Error: Can't resolve 'vue-fineuploader/gallery'
```

**Comment by andresdameson** [comment]
You can import it this way:

import Gallery from 'vue-fineuploader/gallery/index.vue'

**Comment by aiakane16** [comment]
tried it that way, gives me modules not found for all imported components inside index.vue

**Comment by Elhebert** [comment]
And what about in the Vue DevTool? Do you see the components?

**Comment by aiakane16** [comment]
yep it's there, FineUploader then Gallery component

**Comment by Elhebert** [comment]
I'll have to do some tests because I have no idea on why it's happening.

**Comment by aiakane16** [comment]
ok thanks, looking forward to use this .

**Comment by Elhebert** [comment]
It's strange, I can't replicate your error.

I tested the demo code on a brand new Vue project, I had no error in my console, and I had the UI 🤔 
You can check it on CodeSandbox (https://codesandbox.io/s/rm4pjj27pn).

That would mean that it's coming from you code and not the library 🤔
