### ISSUE TITLE
onError, onComplete etc

### ISSUE THREAD

**Issue by MadMikeyB** [FineUploader/vue-fineuploader#50]
Using this implementation do you support callbacks and eventing such as onError, onComplete etc?

Thanks for this btw, great package!

**Comment by Elhebert** [comment]
As stated in the [documentation](https://github.com/FineUploader/vue-fineuploader#wrapper-classes):

> These wrap a Fine Uploader instance for use in Vue Fine Uploader. They provide additional features such as the ability to dynamically register multiple event/callback listeners. All individual and higher-order/focused components require you to pass a constructed wrapper class instance.

More information, such as examples and API documentation, can be found in the README of the fine-uploader-wrappers project.

And if you go check the documentation for the wrappers you will find: https://github.com/FineUploader/fine-uploader-wrappers#oneventname-handlerfunction
