### ISSUE TITLE
contact info please (feel free to sanitize this issue after discussion)

### ISSUE THREAD

**Issue by rnicholus** [FineUploader/vue-fineuploader#60]
Hey @Elhebert - can you provide me with your email address? I'd like to have a discussion re the future of Fine Uploader (i'm not on twitter anymore).

**Comment by Elhebert** [comment]
Sure, you can find it right here: https://github.com/FineUploader/vue-fineuploader/blob/master/package.json#L17

**Comment by rnicholus** [comment]
ah, that's public anyway. Ok, sending you an email now. 

And a summary of my proposal for anyone else interested: I'm considering shutdown/archival of the Fine Uploader project for the following reasons:
1. I no longer have a need for an enterprise-class upload library.
2. I have no motivation to maintain the code (or time).
3. I think the project has outlived its usefulness.
4. I'm tired of defending my inactivity to trolls on Twitter and elsewhere.
